[package]
name = "gitbranchhealth"
version = "0.3.0"
authors = ["Scott Johnson <jaywir3@gmail.com>"]
edition = "2018"
description = "A tool for determining the health of branches in a git repository."

[dependencies]
clap = "2.32.0"
